# Generated by Django 2.2.11 on 2020-03-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='member.Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_idea',
            field=models.ManyToManyField(to='project.ProjectIdea'),
        ),
    ]
