# Generated by Django 2.2.11 on 2020-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_made_description_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='general_models.Framework'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, to='general_models.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(blank=True, to='general_models.Resource'),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='recomended_languages',
            field=models.ManyToManyField(blank=True, to='general_models.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='recommended_frameworks',
            field=models.ManyToManyField(blank=True, to='general_models.Framework'),
        ),
    ]
