# Generated by Django 2.2.11 on 2020-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200308_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectidea',
            old_name='recomended_languages',
            new_name='recommended_languages',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_idea',
            field=models.ManyToManyField(blank=True, to='project.ProjectIdea'),
        ),
    ]
