# Generated by Django 2.2.11 on 2020-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='related_frameworks',
            field=models.ManyToManyField(blank=True, to='general_models.Framework'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15, unique=True),
        ),
    ]
