# Generated by Django 2.2.11 on 2020-03-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslist',
            name='items',
        ),
        migrations.AddField(
            model_name='progresslistitem',
            name='progress_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member_progress.ProgressList'),
            preserve_default=False,
        ),
    ]
