# Generated by Django 2.2.11 on 2020-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_progress', '0002_auto_20200307_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslistitem',
            name='status',
            field=models.CharField(choices=[('todo', 'Planning to do'), ('doing', 'Currently doing'), ('done', 'Done in past')], default='todo', max_length=5),
        ),
    ]
