# Generated by Django 2.2.11 on 2020-03-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_progress', '0003_progress_list_item_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslist',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
